// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";

  var WageWizard;

  window.WageWizard = window.WageWizard || {};

  WageWizard = window.WageWizard;

  WageWizard.FORMULAE = {
    5: [0.0005010000, 6.4000000000, 0.50, 1],
    7: [0.0007107782, 6.4631407136, 0.50, 0.7908],
    2: [0.0009193936, 6.4521801940, 0.50, 0.7762],
    6: [0.0005546901, 6.4374619273, 0.50, 0.8830],
    3: [0.0004312358, 6.4774737732, 0.50, 0.7778],
    4: [0.0008983969, 6.4171590563, 0.50, 0.7917]
  };

}).call(this);
