// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var WageWizard;

  window.WageWizard = window.WageWizard || {};

  WageWizard = window.WageWizard;

  WageWizard.HATTRICK_SKILLS = ['SetPiecesSkill', 'KeeperSkill', 'WingerSkill', 'PassingSkill', 'DefenderSkill', 'ScorerSkill', 'PlaymakerSkill'];

  WageWizard.DISCOUNT_RATE = 0.5;

  WageWizard.KEEPER_FORMULA = [250, 270, 350, 450, 610, 830, 1150, 1610, 2250, 3190, 4550, 6450, 9190, 12930, 18130, 24270, 31720, 41150, 53840, 68750];

  WageWizard.FORMULAE = {
    DefenderSkill: {
      a: 0.0007107782,
      b: 6.4631407136,
      d: 0.7908
    },
    PlaymakerSkill: {
      a: 0.0009359059,
      b: 6.4437872722,
      d: 0.7823
    },
    PassingSkill: {
      a: 0.0003934936,
      b: 6.5741432118,
      d: 0.8127
    },
    WingerSkill: {
      a: 0.0004382320,
      b: 6.4698397687,
      d: 0.7841
    },
    ScorerSkill: {
      a: 0.0009049100,
      b: 6.4135388462,
      d: 0.7950
    }
  };

}).call(this);
