// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var WageWizard, update;

  window.WageWizard = window.WageWizard || {};

  WageWizard = window.WageWizard;

  WageWizard.LEAGUE_DETAILS = {
    1: {
      Country: {
        CountryID: "1",
        CountryName: "Sverige",
        CurrencyName: "kr",
        CurrencyRate: "1",
        DateFormat: "YYYY-MM-DD",
        TimeFormat: "hh:mm"
      }
    },
    2: {
      Country: {
        CountryID: "2",
        CountryName: "England",
        CurrencyName: "£",
        CurrencyRate: "15",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    3: {
      Country: {
        CountryID: "3",
        CountryName: "Deutschland",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    4: {
      Country: {
        CountryID: "4",
        CountryName: "Italia",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh:mm"
      }
    },
    5: {
      Country: {
        CountryID: "5",
        CountryName: "France",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    6: {
      Country: {
        CountryID: "6",
        CountryName: "México",
        CurrencyName: "Pesos",
        CurrencyRate: "1",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    7: {
      Country: {
        CountryID: "7",
        CountryName: "Argentina",
        CurrencyName: "Pesos",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh:mm"
      }
    },
    8: {
      Country: {
        CountryID: "8",
        CountryName: "USA",
        CurrencyName: "US$",
        CurrencyRate: "10",
        DateFormat: "M/D/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    9: {
      Country: {
        CountryID: "9",
        CountryName: "Norge",
        CurrencyName: "Kroner",
        CurrencyRate: "1",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    11: {
      Country: {
        CountryID: "10",
        CountryName: "Danmark",
        CurrencyName: "Kroner",
        CurrencyRate: "1",
        DateFormat: "D/M-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    12: {
      Country: {
        CountryID: "11",
        CountryName: "Suomi",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "D.M.YYYY",
        TimeFormat: "hh.mm"
      }
    },
    14: {
      Country: {
        CountryID: "12",
        CountryName: "Nederland",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    15: {
      Country: {
        CountryID: "13",
        CountryName: "Oceania",
        CurrencyName: "AU$",
        CurrencyRate: "5",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    16: {
      Country: {
        CountryID: "22",
        CountryName: "Brasil",
        CurrencyName: "reais",
        CurrencyRate: "5",
        DateFormat: "D/M/YYYY",
        TimeFormat: "hh:mm"
      }
    },
    17: {
      Country: {
        CountryID: "14",
        CountryName: "Canada",
        CurrencyName: "C$",
        CurrencyRate: "5",
        DateFormat: "M/D/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    18: {
      Country: {
        CountryID: "17",
        CountryName: "Chile",
        CurrencyName: "000 Pesos",
        CurrencyRate: "50",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    19: {
      Country: {
        CountryID: "18",
        CountryName: "Colombia",
        CurrencyName: "US$",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    20: {
      Country: {
        CountryID: "27",
        CountryName: "India",
        CurrencyName: "Rupees",
        CurrencyRate: "0,25",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    21: {
      Country: {
        CountryID: "16",
        CountryName: "Ireland",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    22: {
      Country: {
        CountryID: "25",
        CountryName: "Nippon",
        CurrencyName: "Yen",
        CurrencyRate: "0,1",
        DateFormat: "YYYY-MM-DD",
        TimeFormat: "hh:mm"
      }
    },
    23: {
      Country: {
        CountryID: "21",
        CountryName: "Perú",
        CurrencyName: "US$",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    24: {
      Country: {
        CountryID: "26",
        CountryName: "Polska",
        CurrencyName: "zł",
        CurrencyRate: "2,5",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    25: {
      Country: {
        CountryID: "23",
        CountryName: "Portugal",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    26: {
      Country: {
        CountryID: "15",
        CountryName: "Scotland",
        CurrencyName: "£",
        CurrencyRate: "15",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    27: {
      Country: {
        CountryID: "24",
        CountryName: "South Africa",
        CurrencyName: "Rand",
        CurrencyRate: "1,25",
        DateFormat: "M/D/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    28: {
      Country: {
        CountryID: "19",
        CountryName: "Uruguay",
        CurrencyName: "Pesos",
        CurrencyRate: "1",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    29: {
      Country: {
        CountryID: "20",
        CountryName: "Venezuela",
        CurrencyName: "Bs",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    30: {
      Country: {
        CountryID: "29",
        CountryName: "Hanguk",
        CurrencyName: "000 Won",
        CurrencyRate: "10",
        DateFormat: "YYYY-MM-DD",
        TimeFormat: "hh.mm"
      }
    },
    31: {
      Country: {
        CountryID: "30",
        CountryName: "Prathet Thai",
        CurrencyName: "Baht",
        CurrencyRate: "0,25",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    32: {
      Country: {
        CountryID: "31",
        CountryName: "Türkiye",
        CurrencyName: "TL",
        CurrencyRate: "10",
        DateFormat: "D/M/YYYY",
        TimeFormat: "hh:mm"
      }
    },
    33: {
      Country: {
        CountryID: "32",
        CountryName: "Misr",
        CurrencyName: "E£",
        CurrencyRate: "2,5",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    34: {
      Country: {
        CountryID: "28",
        CountryName: "China",
        CurrencyName: "Yuan",
        CurrencyRate: "1",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    35: {
      Country: {
        CountryID: "34",
        CountryName: "Rossiya",
        CurrencyName: "Roubel",
        CurrencyRate: "0,25",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    36: {
      Country: {
        CountryID: "35",
        CountryName: "España",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh:mm"
      }
    },
    37: {
      Country: {
        CountryID: "36",
        CountryName: "România",
        CurrencyName: "Lei",
        CurrencyRate: "0,5",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    38: {
      Country: {
        CountryID: "37",
        CountryName: "Ísland",
        CurrencyName: "Ikr",
        CurrencyRate: "0,1",
        DateFormat: "D/M/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    39: {
      Country: {
        CountryID: "33",
        CountryName: "Österreich",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    44: {
      Country: {
        CountryID: "38",
        CountryName: "Belgium",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    45: {
      Country: {
        CountryID: "39",
        CountryName: "Malaysia",
        CurrencyName: "MYR",
        CurrencyRate: "2,5",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    46: {
      Country: {
        CountryID: "40",
        CountryName: "Schweiz",
        CurrencyName: "CHF",
        CurrencyRate: "5",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    47: {
      Country: {
        CountryID: "41",
        CountryName: "Singapore",
        CurrencyName: "SG$",
        CurrencyRate: "5",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    50: {
      Country: {
        CountryID: "45",
        CountryName: "Hellas",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "D/M/YYYY",
        TimeFormat: "hh:mm"
      }
    },
    51: {
      Country: {
        CountryID: "44",
        CountryName: "Magyarország",
        CurrencyName: "eFt",
        CurrencyRate: "50",
        DateFormat: "YYYY-MM-DD",
        TimeFormat: "hh:mm"
      }
    },
    52: {
      Country: {
        CountryID: "46",
        CountryName: "Česká republika",
        CurrencyName: "Kč",
        CurrencyRate: "0,25",
        DateFormat: "D.M.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    53: {
      Country: {
        CountryID: "48",
        CountryName: "Latvija",
        CurrencyName: "Lats",
        CurrencyRate: "20",
        DateFormat: "DD.MM.YYYY.",
        TimeFormat: "hh:mm"
      }
    },
    54: {
      Country: {
        CountryID: "49",
        CountryName: "Indonesia",
        CurrencyName: "000 Rp",
        CurrencyRate: "1",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    55: {
      Country: {
        CountryID: "50",
        CountryName: "Pilipinas",
        CurrencyName: "Pesos",
        CurrencyRate: "0,25",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    56: {
      Country: {
        CountryID: "47",
        CountryName: "Eesti",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    57: {
      Country: {
        CountryID: "43",
        CountryName: "Srbija",
        CurrencyName: "dinar",
        CurrencyRate: "1",
        DateFormat: "DD.MM.YYYY.",
        TimeFormat: "hh:mm"
      }
    },
    58: {
      Country: {
        CountryID: "42",
        CountryName: "Hrvatska",
        CurrencyName: "Kuna",
        CurrencyRate: "1",
        DateFormat: "DD.MM.YYYY.",
        TimeFormat: "hh:mm"
      }
    },
    59: {
      Country: {
        CountryID: "53",
        CountryName: "Hong Kong SAR",
        CurrencyName: "HKD",
        CurrencyRate: "1",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    60: {
      Country: {
        CountryID: "52",
        CountryName: "Chinese Taipei",
        CurrencyName: "$",
        CurrencyRate: "10",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    61: {
      Country: {
        CountryID: "56",
        CountryName: "Cymru",
        CurrencyName: "£",
        CurrencyRate: "15",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    62: {
      Country: {
        CountryID: "55",
        CountryName: "Bulgaria",
        CurrencyName: "lv",
        CurrencyRate: "5",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh.mm"
      }
    },
    63: {
      Country: {
        CountryID: "51",
        CountryName: "Israel",
        CurrencyName: "NIS",
        CurrencyRate: "2",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    64: {
      Country: {
        CountryID: "57",
        CountryName: "Slovenija",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    66: {
      Country: {
        CountryID: "61",
        CountryName: "Lietuva",
        CurrencyName: "Lt",
        CurrencyRate: "2,5",
        DateFormat: "YYYY-MM-DD",
        TimeFormat: "hh:mm"
      }
    },
    67: {
      Country: {
        CountryID: "66",
        CountryName: "Slovensko",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "D.M.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    68: {
      Country: {
        CountryID: "62",
        CountryName: "Ukraina",
        CurrencyName: "hryvnia",
        CurrencyRate: "2",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    69: {
      Country: {
        CountryID: "63",
        CountryName: "Bosna i Hercegovina",
        CurrencyName: "KM",
        CurrencyRate: "5",
        DateFormat: "DD.MM.YYYY.",
        TimeFormat: "hh:mm"
      }
    },
    70: {
      Country: {
        CountryID: "65",
        CountryName: "Việt Nam",
        CurrencyName: "đồng",
        CurrencyRate: "1",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    71: {
      Country: {
        CountryID: "64",
        CountryName: "Pakistan",
        CurrencyName: "rupee",
        CurrencyRate: "0,2",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    72: {
      Country: {
        CountryID: "67",
        CountryName: "Paraguay",
        CurrencyName: "000 PYG",
        CurrencyRate: "2",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    73: {
      Country: {
        CountryID: "68",
        CountryName: "Ecuador",
        CurrencyName: "$",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    74: {
      Country: {
        CountryID: "69",
        CountryName: "Bolivia",
        CurrencyName: "Bs",
        CurrencyRate: "1",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    75: {
      Country: {
        CountryID: "70",
        CountryName: "Nigeria",
        CurrencyName: "kNaira",
        CurrencyRate: "0,1",
        DateFormat: "M/D/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    76: {
      Country: {
        CountryID: "71",
        CountryName: "Føroyar",
        CurrencyName: "Kroner",
        CurrencyRate: "1",
        DateFormat: "M/D/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    77: {
      Country: {
        CountryID: "72",
        CountryName: "Al Maghrib",
        CurrencyName: "dirhams",
        CurrencyRate: "1",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    79: {
      Country: {
        CountryID: "75",
        CountryName: "Saudi Arabia",
        CurrencyName: "SAR",
        CurrencyRate: "2,5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    80: {
      Country: {
        CountryID: "76",
        CountryName: "Tounes",
        CurrencyName: "Dinars",
        CurrencyRate: "8",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    81: {
      Country: {
        CountryID: "77",
        CountryName: "Costa Rica",
        CurrencyName: "Colones",
        CurrencyRate: "0,2",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    83: {
      Country: {
        CountryID: "78",
        CountryName: "United Arab Emirates",
        CurrencyName: "Dirham",
        CurrencyRate: "4",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    84: {
      Country: {
        CountryID: "79",
        CountryName: "Lëtzebuerg",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "D.M.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    85: {
      Country: {
        CountryID: "80",
        CountryName: "Iran",
        CurrencyName: "000 Rial",
        CurrencyRate: "1",
        DateFormat: "YYYY-MM-DD",
        TimeFormat: "hh:mm"
      }
    },
    88: {
      Country: {
        CountryID: "83",
        CountryName: "República Dominicana",
        CurrencyName: "pesos",
        CurrencyRate: "0,5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    89: {
      Country: {
        CountryID: "82",
        CountryName: "Cyprus",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    91: {
      Country: {
        CountryID: "87",
        CountryName: "Belarus",
        CurrencyName: "000 BYR",
        CurrencyRate: "5",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    93: {
      Country: {
        CountryID: "88",
        CountryName: "Northern Ireland",
        CurrencyName: "£",
        CurrencyRate: "15",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    94: {
      Country: {
        CountryID: "89",
        CountryName: "Jamaica",
        CurrencyName: "JMD",
        CurrencyRate: "0,5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    95: {
      Country: {
        CountryID: "90",
        CountryName: "Kenya",
        CurrencyName: "KES",
        CurrencyRate: "0,5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    96: {
      Country: {
        CountryID: "91",
        CountryName: "Panamá",
        CurrencyName: "฿",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    97: {
      Country: {
        CountryID: "92",
        CountryName: "Makedonija",
        CurrencyName: "MKD",
        CurrencyRate: "0,5",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    98: {
      Country: {
        CountryID: "94",
        CountryName: "Shqipëria",
        CurrencyName: "000 lek",
        CurrencyRate: "50",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    99: {
      Country: {
        CountryID: "95",
        CountryName: "Honduras",
        CurrencyName: "HNL",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    100: {
      Country: {
        CountryID: "96",
        CountryName: "El Salvador",
        CurrencyName: "US$",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    101: {
      Country: {
        CountryID: "97",
        CountryName: "Malta",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    102: {
      Country: {
        CountryID: "98",
        CountryName: "Kyrgyzstan",
        CurrencyName: "som",
        CurrencyRate: "0,2",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    103: {
      Country: {
        CountryID: "99",
        CountryName: "Moldova",
        CurrencyName: "lei",
        CurrencyRate: "0,5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    104: {
      Country: {
        CountryID: "100",
        CountryName: "Sakartvelo",
        CurrencyName: "Lari",
        CurrencyRate: "5",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    105: {
      Country: {
        CountryID: "101",
        CountryName: "Andorra",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    106: {
      Country: {
        CountryID: "103",
        CountryName: "Al Urdun",
        CurrencyName: "JOD",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    107: {
      Country: {
        CountryID: "102",
        CountryName: "Guatemala",
        CurrencyName: "Q",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    110: {
      Country: {
        CountryID: "105",
        CountryName: "Trinidad & Tobago",
        CurrencyName: "TTD",
        CurrencyRate: "1",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    111: {
      Country: {
        CountryID: "121",
        CountryName: "Nicaragua",
        CurrencyName: "NIO",
        CurrencyRate: "0,5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    112: {
      Country: {
        CountryID: "122",
        CountryName: "Kazakhstan",
        CurrencyName: "tenge",
        CurrencyRate: "0,1",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    113: {
      Country: {
        CountryID: "123",
        CountryName: "Suriname",
        CurrencyName: "SRD",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    117: {
      Country: {
        CountryID: "125",
        CountryName: "Liechtenstein",
        CurrencyName: "CHF",
        CurrencyRate: "5",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    118: {
      Country: {
        CountryID: "126",
        CountryName: "Algérie",
        CurrencyName: "DZD",
        CurrencyRate: "0,1",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    119: {
      Country: {
        CountryID: "127",
        CountryName: "Mongol Uls",
        CurrencyName: "000 tugrik",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    120: {
      Country: {
        CountryID: "128",
        CountryName: "Lebanon",
        CurrencyName: "000 LBP",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    121: {
      Country: {
        CountryID: "86",
        CountryName: "Sénégal",
        CurrencyName: "000 XOF",
        CurrencyRate: "20",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    122: {
      Country: {
        CountryID: "104",
        CountryName: "Armenia",
        CurrencyName: "000 dram",
        CurrencyRate: "20",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    123: {
      Country: {
        CountryID: "129",
        CountryName: "Bahrain",
        CurrencyName: "BHD",
        CurrencyRate: "20",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    124: {
      Country: {
        CountryID: "130",
        CountryName: "Barbados",
        CurrencyName: "BBD",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    125: {
      Country: {
        CountryID: "131",
        CountryName: "Cabo Verde",
        CurrencyName: "Esc.",
        CurrencyRate: "0,1",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    126: {
      Country: {
        CountryID: "132",
        CountryName: "Côte d’Ivoire",
        CurrencyName: "000 XOF",
        CurrencyRate: "20",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    127: {
      Country: {
        CountryID: "134",
        CountryName: "Al Kuwayt",
        CurrencyName: "dinar",
        CurrencyRate: "25",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    128: {
      Country: {
        CountryID: "135",
        CountryName: "Al Iraq",
        CurrencyName: "dinar",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    129: {
      Country: {
        CountryID: "133",
        CountryName: "Azərbaycan",
        CurrencyName: "AZN",
        CurrencyRate: "10",
        DateFormat: "DD.MM.YYYY",
        TimeFormat: "hh:mm"
      }
    },
    130: {
      Country: {
        CountryID: "137",
        CountryName: "Angola",
        CurrencyName: "kwanza",
        CurrencyRate: "0,1",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh:mm"
      }
    },
    131: {
      Country: {
        CountryID: "136",
        CountryName: "Crna Gora",
        CurrencyName: "€",
        CurrencyRate: "10",
        DateFormat: "DD.MM.YYYY.",
        TimeFormat: "hh:mm"
      }
    },
    132: {
      Country: {
        CountryID: "138",
        CountryName: "Bangladesh",
        CurrencyName: "taka",
        CurrencyRate: "0,2",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    133: {
      Country: {
        CountryID: "139",
        CountryName: "Al Yaman",
        CurrencyName: "rial",
        CurrencyRate: "0,1",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    134: {
      Country: {
        CountryID: "140",
        CountryName: "Oman",
        CurrencyName: "rial",
        CurrencyRate: "20",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    135: {
      Country: {
        CountryID: "142",
        CountryName: "Moçambique",
        CurrencyName: "metical",
        CurrencyRate: "0,4",
        DateFormat: "DD/MM/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    136: {
      Country: {
        CountryID: "143",
        CountryName: "Brunei",
        CurrencyName: "BND",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    137: {
      Country: {
        CountryID: "144",
        CountryName: "Ghana",
        CurrencyName: "cedis",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    138: {
      Country: {
        CountryID: "145",
        CountryName: "Kampuchea",
        CurrencyName: "Riel",
        CurrencyRate: "0,0025",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    139: {
      Country: {
        CountryID: "147",
        CountryName: "Benin",
        CurrencyName: "$",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    140: {
      Country: {
        CountryID: "148",
        CountryName: "Suriyah",
        CurrencyName: "$",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    141: {
      Country: {
        CountryID: "149",
        CountryName: "Qatar",
        CurrencyName: "QAR",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    142: {
      Country: {
        CountryID: "150",
        CountryName: "Tanzania",
        CurrencyName: "$",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    143: {
      Country: {
        CountryID: "153",
        CountryName: "Uganda",
        CurrencyName: "000 shill",
        CurrencyRate: "5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    144: {
      Country: {
        CountryID: "154",
        CountryName: "Dhivehi Raajje",
        CurrencyName: "rufiyaa",
        CurrencyRate: "0,5",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    145: {
      Country: {
        CountryID: "163",
        CountryName: "Uzbekistan",
        CurrencyName: "000 som",
        CurrencyRate: "10",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    146: {
      Country: {
        CountryID: "165",
        CountryName: "Cameroon",
        CurrencyName: "000 XAF",
        CurrencyRate: "20",
        DateFormat: "DD-MM-YYYY",
        TimeFormat: "hh.mm"
      }
    },
    147: {
      Country: {
        CountryID: "93",
        CountryName: "Cuba",
        CurrencyName: "$",
        CurrencyRate: "10",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    },
    148: {
      Country: {
        CountryID: "166",
        CountryName: "Palestine",
        CurrencyName: "NIS",
        CurrencyRate: "2",
        DateFormat: "MM/DD/YYYY",
        TimeFormat: "hh.mm"
      }
    }
  };

  update = function() {
    var league, _i, _len, _ref;
    _ref = HattrickData.LeagueList.League;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      league = _ref[_i];
      leagueDetails[league.LeagueID].Country = league.Country;
    }
    return console.log(JSON.stringify(leagueDetails));
  };

}).call(this);
